# Generated by Django 3.0.6 on 2020-06-09 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('row', models.IntegerField(null=True)),
                ('column', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sit',
            fields=[
                ('sit_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('missed_time', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('u', 'Use'), ('m', 'Missed'), ('a', 'Available')], default='a', help_text='Present Sit Status', max_length=1)),
            ],
        ),
    ]
