# Generated by Django 3.0.6 on 2020-06-09 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudyroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('missed_time', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('u', 'Use'), ('m', 'Missed'), ('a', 'Available')], default='a', help_text='Present Sit Status', max_length=1)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartstudyroom.Room')),
            ],
        ),
        migrations.DeleteModel(
            name='sit',
        ),
    ]
