# Generated by Django 3.0.6 on 2020-06-19 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartstudyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='present_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'Use'), ('a', 'Available')], default='a', help_text='Present Sit Status', max_length=1),
        ),
    ]
