# Generated by Django 3.0.6 on 2020-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudyroom', '0002_auto_20200609_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='missed_time',
            field=models.FloatField(null=True),
        ),
    ]
