# Generated by Django 3.0.6 on 2020-06-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudyroom', '0002_auto_20200619_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='missed_time',
        ),
    ]
