# Generated by Django 3.0.6 on 2020-06-23 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudyroom', '0003_remove_seat_missed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='present_user',
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'Use'), ('r', 'Reserve'), ('a', 'Available')], default='a', help_text='Present Sit Status', max_length=1),
        ),
    ]
